// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"
)

type User struct {
	ID        string
	Createdat time.Time
	Updateat  time.Time
	Name      string
}
