// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (
  id, createdAt, updateAt, name
)  VALUES(
  ?, ?, ?,?
)
`

type CreateUserParams struct {
	ID        string
	Createdat time.Time
	Updateat  time.Time
	Name      string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Createdat,
		arg.Updateat,
		arg.Name,
	)
}
